services:
  # PostgreSQL => Auth Service
  postgres-auth:
    image: postgres:15-alpine
    container_name: reservehub-postgres-auth
    environment:
      POSTGRES_DB: auth_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
    ports:
      - "5431:5432"
    volumes:
      - postgres-auth-data:/var/lib/postgresql/data
    networks:
      - reservehub-network

  # PostgreSQL => Booking Service
  postgres-booking:
    image: postgres:15-alpine
    container_name: reservehub-postgres-booking
    environment:
      POSTGRES_DB: booking_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
    ports:
      - "5433:5432"
    volumes:
      - postgres-booking-data:/var/lib/postgresql/data
    networks:
      - reservehub-network

  # Redis => Caching
  redis:
    image: redis:7-alpine
    container_name: reservehub-redis
    ports:
      - "6379:6379"
    networks:
      - reservehub-network

  # Kafka
  kafka:
    image: apache/kafka:3.7.0
    container_name: kafka
    ports:
      - "9092:9092"
    volumes:
      - kafka-data:/var/lib/kafka/data
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      CLUSTER_ID: "5L6g3nShT-eMCtK--X86sw"
    networks:
      - reservehub-network

  # Kafka UI (Optional)
  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: reservehub-kafka-ui
    depends_on:
      - kafka
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092
    ports:
      - "8085:8080"
    networks:
      - reservehub-network

networks:
  reservehub-network:
    driver: bridge

volumes:
  postgres-auth-data:
  postgres-booking-data:
  kafka-data: